config/routes.rb
Rails.application.routes.draw do
  get 'experiment/page1'

  get 'experiment/page2'

  get 'experiment/page3'

  get 'pages/batman'

  get 'pages/superman'

  get 'pages/batman-vs-superman'

  resources :votes 

  root 'pages#batman-vs-superman'

end

app/models/vote.rb
class Vote < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/experiment_controller.rb
class ExperimentController < ApplicationController
  layout "bootstrap"

  def page1
  end

  def page2
  end

  def page3
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def batman
  end

  def superman
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  before_action :set_vote, only: [:show, :edit, :update, :destroy]

  def index
    @votes =  Vote.all
  end

  def new
    @vote = Vote.new
  end

  def create
    @vote = Vote.new(vote_params)
    return redirect_to votes_path if @vote.save
    render :new
  end

  def edit
  end

  def update
    return redirect_to items_path if @vote.update(vote_params)
    render :edit

  end

  def show
  end

  def destroy
    @vote.destroy()
    redirect_to votes_path
  end

  private

  def set_vote
    @vote = Vote.find(params[:id])
  end

  def vote_params
    params.require(:vote).permit(:email, :heroe)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/experiment_helper.rb
module ExperimentHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/experiment/page1.html.erb
<body class="experiments page1">
  <h1>Page 1</h1>
  <p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magniSed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magniSed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magniSed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni</p>

  <p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni</p>
</body>

app/views/experiment/page2.html.erb
<body class="experiments page2">
  <h1>Page 2</h1>
  <p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magniSed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magniSed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magniSed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni</p>

  <p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni</p>
  <button type="button" onclick="countdown()" name="button">countdown in console</button>
</body>
<script>
var time = 400

function countdown() {
    inter = setInterval(count, 100);
}
function count() {
  time = time - 1;
  console.log(time)

}


</script

app/views/experiment/page3.html.erb
<body class="experiments page3">
  <h1>Page 3</h1>
  <p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magniSed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magniSed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magniSed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni</p>

  <p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni</p>
</body>

app/views/layouts/_menu.html.erb
<div class="container">
  <%= link_to "Page 1", experiment_page1_path, class: "btn btn-default" %>
  <%= link_to "Page 2", experiment_page2_path, class: "btn btn-default" %>
  <%= link_to "Page 3", experiment_page3_path, class: "btn btn-default" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Superheroes</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag "pages/batman.html.erb" %>
  <%= stylesheet_link_tag "pages/superman.html.erb" %>
  <%= stylesheet_link_tag "pages/batman-vs-superman.html.erb" %>

  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/bootstrap.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bootstrap</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render "layouts/menu" %>
  <%= yield %>

</body>
</html>

app/views/pages/batman-vs-superman.html.erb
<div class="container-fluid">
  <div class="heroeSec col-xs-6">
    <div class="">
      <%=link_to image_tag("batmanback.jpg"), pages_batman_path , class: "img-responsive" %>
    </div>

  </div>
  <div class="heroeSec col-xs-6">
    <div class="">
      <%= link_to image_tag("supermanback.jpg"), pages_superman_path , class: "img-responsive fullfit" %>
    </div>
    <div class="container">
      <form class="" action="index.html" method="post">

      </form>
    </div>
  </div>
</div>

app/views/pages/batman.html.erb
<div class="container-fluid batman">
  <div class="box">
    <h1>I am batman</h1>
  </div>
</div>

app/views/pages/superman.html.erb
<div class="container-fluid superman">
  <div class="box">
    <h1> This looks like a job for superman</h1>
  </div>
</div>